name: Deploy Web & Admin to Vercel (manual-selectable)

on:
  workflow_dispatch:
    inputs:
      target:
        description: "배포할 앱 선택"
        required: true
        default: "all"
        type: choice
        options: [all, web, admin]

jobs:
  deploy-web:
    if: github.event.inputs.target == 'all' || github.event.inputs.target == 'web'
    runs-on: ubuntu-latest
    concurrency: web-prod
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB }}
      PROD_ALIAS: "web.dddorok.vercel.app"
      HEALTH_PATH: "/health"

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with: { version: 10 }

      - run: pnpm install --frozen-lockfile

      - name: Clean up old .vercel for Web
        run: rm -rf apps/web/.vercel

      - name: Vercel Pull (Web)
        run: |
          npx vercel pull \
            --cwd apps/web \
            --yes \
            --environment=production \
            --token $VERCEL_TOKEN

      - name: Vercel Build (Web)
        run: |
          npx vercel build \
            --cwd apps/web \
            --prod \
            --token $VERCEL_TOKEN

      - name: DEBUG - where is Web output?
        run: |
          BASE="$GITHUB_WORKSPACE/apps/web/.vercel"
          echo "📂 $BASE:"
          ls -al "$BASE" || true

          OUT="$BASE/output"
          echo "📂 $OUT:"
          ls -al "$OUT" || true

      - name: Vercel Deploy (Web)
        id: deploy-web
        run: |
          # 프로젝트 루트 인자
          PROJECT_ROOT="$GITHUB_WORKSPACE/apps/web"
          echo "Deploying project at $PROJECT_ROOT"
          url=$(
          npx vercel deploy \
            --prebuilt \
            --prod \
            --token $VERCEL_TOKEN \
            "$GITHUB_WORKSPACE"
          )
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Smoke test & auto-rollback (Web)
        run: |
          target="${{ steps.deploy-web.outputs.url }}$HEALTH_PATH"
          echo "Health-check → $target"
          code=$(curl -s -o /dev/null -w "%{http_code}" "$target")
          if [ "$code" != "200" ]; then
            echo "❌ Health-check failed ($code) → rolling back"
            prev=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" \
              "https://api.vercel.com/v6/deployments?projectId=$VERCEL_PROJECT_ID&limit=2&state=READY" \
              | jq -r '.deployments[1].uid')
            curl -s -X POST -H "Authorization: Bearer $VERCEL_TOKEN" \
              -H "Content-Type: application/json" \
              "https://api.vercel.com/v2/aliases" \
              -d "{\"deploymentId\":\"$prev\",\"alias\":\"$PROD_ALIAS\"}"
            exit 1
          else
            echo "✅ Health-check OK"
          fi

  deploy-admin:
    if: github.event.inputs.target == 'all' || github.event.inputs.target == 'admin'
    runs-on: ubuntu-latest
    concurrency: admin-prod
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_ADMIN }}
      PROD_ALIAS: "admin.dddorok.vercel.app"
      HEALTH_PATH: "/health"

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with: { version: 10 }

      - run: pnpm install --frozen-lockfile

      - name: Clean up old .vercel for Admin
        run: rm -rf apps/admin/.vercel

      - name: Vercel Pull (Admin)
        run: |
          npx vercel pull \
            --cwd apps/admin \
            --yes \
            --environment=production \
            --token $VERCEL_TOKEN

      - name: Vercel Build (Admin)
        run: |
          npx vercel build \
            --cwd apps/admin \
            --prod \
            --token $VERCEL_TOKEN

      - name: DEBUG – where is Admin output?
        run: |
          echo "📂 apps/admin/.vercel:"
          ls -al apps/admin/.vercel || true
          echo "📂 apps/admin/.vercel/output:"
          ls -al apps/admin/.vercel/output || true

      - name: Vercel Deploy (Admin)
        id: deploy-admin
        run: |
          url=$(npx vercel deploy \
            --cwd apps/admin \
            .vercel/output \
            --prebuilt \
            --prod \
            --token $VERCEL_TOKEN)
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Smoke test & auto-rollback (Admin)
        run: |
          target="${{ steps.deploy-admin.outputs.url }}$HEALTH_PATH"
          code=$(curl -s -o /dev/null -w "%{http_code}" "$target")
          if [ "$code" != "200" ]; then
            echo "❌ Health-check failed ($code) → rolling back"
            prev=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" \
              "https://api.vercel.com/v6/deployments?projectId=$VERCEL_PROJECT_ID&limit=2&state=READY" \
              | jq -r '.deployments[1].uid')
            curl -s -X POST -H "Authorization: Bearer $VERCEL_TOKEN" \
              -H "Content-Type: application/json" \
              "https://api.vercel.com/v2/aliases" \
              -d "{\"deploymentId\":\"$prev\",\"alias\":\"$PROD_ALIAS\"}"
            exit 1
          else
            echo "✅ Health-check OK"
          fi
